# Generated by Django 3.2.6 on 2021-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgroup',
            name='configFile',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл конфигурации для группы'),
        ),
        migrations.AlterField(
            model_name='globalgroup',
            name='loginGroup',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Логин для микротиков, принадлежащих этой группе'),
        ),
        migrations.AlterField(
            model_name='globalgroup',
            name='passGroup',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль для микротиков, принадлежащих этой группе'),
        ),
        migrations.AlterField(
            model_name='group',
            name='configFile',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл конфигурации для подгруппы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='loginGroup',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Логин для микротиков, принадлежащих этой подгруппе'),
        ),
        migrations.AlterField(
            model_name='group',
            name='passGroup',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль для микротиков, принадлежащих этой подгруппе'),
        ),
        migrations.AlterField(
            model_name='mikrot',
            name='mikrotLogin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Логин Микротик'),
        ),
        migrations.AlterField(
            model_name='mikrot',
            name='mikrotPass',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль Микротик'),
        ),
    ]
